;; Diagnostic ONLY: closed stock JSON shapes, default escaping, no protocol
;; extensions/callbacks. Not a replacement for the public data.json writer.
;; One invocation owns one bounded byte buffer; no payload state survives it.
(define direct-bytes-method-cell (jolt-var "clojure.data.json" "-write"))
(define direct-bytes-method-site
  (make-protocol-method-site "clojure.data.json/JSONWriter" "-write"))
(lambda (rows limit stock)
  (unless (and (pvec? rows) (fixnum? limit) (fx>=? limit 0))
    (error 'direct-bytes "invalid rows or limit"))
  (unless (or (jolt-nil? stock)
              (and (pvec? stock) (fx=? (pvec-count stock) 11)
                   (eq? (pvec-nth! stock 10)
                        (keyword "clojure.data.json" "native-writer-v1"))))
    (error 'direct-bytes "stock ABI mismatch"))
  (let ((buf (make-bytevector (min limit 4096))) (used 0))
    (define (reserve! n)
      (let ((need (+ used n)))
        (when (> need limit) (error 'direct-bytes "byte budget exceeded"))
        (when (> need (bytevector-length buf))
          (let ((next (make-bytevector
                        (min limit (max need (* 2 (max 1 (bytevector-length buf))))))))
            (bytevector-copy! buf 0 next 0 used)
            (set! buf next)))))
    (define (byte! b)
      (reserve! 1)
      (bytevector-u8-set! buf used b)
      (set! used (fx+ used 1)))
    (define (ascii! s)
      (let ((n (string-length s)))
        (reserve! n)
        (do ((i 0 (fx+ i 1))) ((fx=? i n))
          (bytevector-u8-set! buf (fx+ used i) (char->integer (string-ref s i))))
        (set! used (fx+ used n))))
    (define (u16! cp)
      (ascii! "\\u")
      (do ((shift 12 (fx- shift 4))) ((fx<? shift 0))
        (let ((n (fxand (fxsra cp shift) 15)))
          (byte! (if (fx<? n 10) (fx+ 48 n) (fx+ 87 n))))))
    (define (string! s)
      (byte! 34)
      (do ((i 0 (fx+ i 1))) ((fx=? i (string-length s)))
        (let ((cp (char->integer (string-ref s i))))
          (case cp
            ((34 92 47) (byte! 92) (byte! cp))
            ((8) (ascii! "\\b")) ((12) (ascii! "\\f"))
            ((10) (ascii! "\\n")) ((13) (ascii! "\\r")) ((9) (ascii! "\\t"))
            (else
              (cond ((or (fx<? cp 32) (fx>? cp 127))
                     (cond ((<= #xd800 cp #xdfff)
                            (error 'direct-bytes "non-scalar string"))
                           ((fx<=? cp #xffff) (u16! cp))
                           (else (let ((n (fx- cp #x10000)))
                                   (u16! (fx+ #xd800 (fxsra n 10)))
                                   (u16! (fx+ #xdc00 (fxand n #x3ff)))))))
                    (else (byte! cp)))))))
      (byte! 34))
    (define (integer! n)
      ;; Write digits backward into reusable batch scratch, including MIN_INT
      ;; without negating the full magnitude. No per-integer decimal string.
      (let ((negative? (< n 0)))
        (let digits ((x n) (i 20))
          (let ((q (quotient x 10)) (r (remainder x 10)))
            (bytevector-u8-set! scratch i (+ 48 (abs r)))
            (if (= q 0)
                (let* ((start (if negative? (- i 1) i)) (len (- 21 start)))
                  (when negative? (bytevector-u8-set! scratch start 45))
                  (reserve! len)
                  (bytevector-copy! scratch start buf used len)
                  (set! used (+ used len)))
                (digits q (- i 1)))))))
    (define scratch (make-bytevector 21))
    (define (emit! x)
      ;; Optional diagnostic arm restores core-owned LIVE dispatch checks.
      ;; Custom extensions are explicitly rejected, never ignored or restarted.
      ;; This is still not a public writer: it has no callback-capable sink.
      (unless (jolt-nil? stock)
        (unless (eq? (var-cell-root direct-bytes-method-cell) (pvec-nth! stock 0))
          (error 'direct-bytes "dispatcher changed"))
        (let ((impl (direct-bytes-method-site x)))
          (unless
            (cond ((jolt-nil? x) (eq? impl (pvec-nth! stock 1)))
                  ((boolean? x) (eq? impl (pvec-nth! stock 2)))
                  ((and (integer? x) (exact? x))
                   (or (eq? impl (pvec-nth! stock 2)) (eq? impl (pvec-nth! stock 4))))
                  ((flonum? x) (eq? impl (pvec-nth! stock 3)))
                  ((string? x) (eq? impl (pvec-nth! stock 6)))
                  ((pmap? x) (eq? impl (pvec-nth! stock 7)))
                  ((pvec? x) (eq? impl (pvec-nth! stock 8)))
                  (else (error 'direct-bytes "unsupported diagnostic value")))
            (error 'direct-bytes "non-stock writer"))))
      (cond ((jolt-nil? x) (ascii! "null"))
            ((string? x) (string! x))
            ((boolean? x) (ascii! (if x "true" "false")))
            ((and (integer? x) (exact? x)
                  (<= -9223372036854775808 x 18446744073709551615)) (integer! x))
            ((and (flonum? x) (finite? x)) (ascii! (jolt-flonum->string x)))
            ((pvec? x)
             (byte! 91)
             (do ((i 0 (fx+ i 1))) ((fx=? i (pvec-count x)))
               (unless (fx=? i 0) (byte! 44))
               (emit! (pvec-nth! x i)))
             (byte! 93))
            ((pmap? x)
             (byte! 123)
             (pmap-fold-seq-order x
               (lambda (k v first?)
                 (unless (string? k) (error 'direct-bytes "non-string key"))
                 (unless first? (byte! 44))
                 (string! k) (byte! 58) (emit! v) #f) #t)
             (byte! 125))
            (else (error 'direct-bytes "unsupported diagnostic value"))))
    (do ((i 0 (fx+ i 1))) ((fx=? i (pvec-count rows)))
      (emit! (pvec-nth! rows i)) (byte! 10))
    ;; Include the final ownership copy in measurements; no alias of mutable
    ;; capacity escapes. No connection/WAL/ACK logic is involved here.
    (let ((out (make-bytevector used)))
      (bytevector-copy! buf 0 out 0 used)
      (na-bv->bytearray out))))
